package ui

import (
	"fmt"
	"komiku-scraper/scraper/komiku"
	"log"
	"os"
	"os/exec"
)

// OpenInBrowser makes an HTML file and opens it
func OpenInBrowser(title string, images []komiku.ChapterImage) {
	filename := "reader.html"
	f, err := os.Create(filename)
	if err != nil {
		log.Println("Error creating HTML:", err)
		return
	}
	defer f.Close()

	htmlContent := fmt.Sprintf(`<!DOCTYPE html>
<html>
<head>
	<title>%s - Komiku Reader</title>
	<style>
		body { background-color: #1a1a1a; margin: 0; padding: 20px; text-align: center; }
		img { max-width: 100%%; height: auto; display: block; margin: 10px auto; box-shadow: 0 0 10px rgba(0,0,0,0.5); }
		h1 { color: white; font-family: sans-serif; }
		.nav { position: fixed; bottom: 20px; right: 20px; background: rgba(0,0,0,0.8); color: white; padding: 10px; border-radius: 5px; }
	</style>
</head>
<body>
	<h1>%s</h1>
`, title, title)

	for _, img := range images {
		htmlContent += fmt.Sprintf("\t<img src=\"%s\" loading=\"lazy\" />\n", img.URL)
	}

	htmlContent += `	<div class="nav">Generated by Komiku Scraper Bot</div>
</body>
</html>`

	f.WriteString(htmlContent)
	fmt.Println("Membuka browser...")

	// Command for Windows
	exec.Command("cmd", "/C", "start", filename).Start()
}

// OpenURL opens the default browser with the specified URL
func OpenURL(url string) {
	fmt.Printf("Membuka %s di browser default...\n", url)
	err := exec.Command("cmd", "/C", "start", url).Start()
	if err != nil {
		log.Printf("Gagal membuka browser: %v\n", err)
	}
}
